[package]
name = "content-scraper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scraper="0.16.0"
strum_macros = "0.24.3"
url="2.3.1"